/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Patient;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel bottomPanel;
    public FormPanel(JPanel inputPanel) {
        initComponents();
        this.bottomPanel = inputPanel;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FnameLabel = new javax.swing.JLabel();
        LnameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        MessageLabel = new javax.swing.JLabel();
        FnameTxtField = new javax.swing.JTextField();
        LnameTxtField = new javax.swing.JTextField();
        AgeTxtField = new javax.swing.JTextField();
        EmailTxtField = new javax.swing.JTextField();
        MessageTxtFIeld = new javax.swing.JTextField();
        Submitbutton = new javax.swing.JButton();
        GenderLabel = new javax.swing.JLabel();
        MaleRadioButon = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        OtherRadioButton = new javax.swing.JRadioButton();
        patientTypeLabel = new javax.swing.JLabel();
        patientCombobox = new javax.swing.JComboBox<>();
        ImageButton = new javax.swing.JButton();
        Imagedisplay = new javax.swing.JLabel();

        MainPanel.setBackground(new java.awt.Color(255, 255, 204));
        MainPanel.setPreferredSize(new java.awt.Dimension(450, 500));

        Title.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Title.setText("Customer Registration Form");

        FnameLabel.setText("First Name");

        LnameLabel.setText("Last Name");

        AgeLabel.setText("Age");

        EmailLabel.setText("Email");

        MessageLabel.setText("Message");

        FnameTxtField.setText(" ");
        FnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FnameTxtFieldFocusLost(evt);
            }
        });

        LnameTxtField.setText(" ");
        LnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameTxtFieldFocusLost(evt);
            }
        });
        LnameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameTxtFieldActionPerformed(evt);
            }
        });

        AgeTxtField.setText(" ");
        AgeTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AgeTxtFieldFocusLost(evt);
            }
        });

        EmailTxtField.setText(" ");
        EmailTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailTxtFieldFocusLost(evt);
            }
        });

        MessageTxtFIeld.setText(" ");
        MessageTxtFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageTxtFIeldActionPerformed(evt);
            }
        });

        Submitbutton.setText("Submit");
        Submitbutton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SubmitbuttonFocusLost(evt);
            }
        });
        Submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttonActionPerformed(evt);
            }
        });

        GenderLabel.setText("Gender");

        GenderButtonGroup.add(MaleRadioButon);
        MaleRadioButon.setText("Male");
        MaleRadioButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButonActionPerformed(evt);
            }
        });

        GenderButtonGroup.add(FemaleRadioButton);
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioButtonActionPerformed(evt);
            }
        });

        GenderButtonGroup.add(OtherRadioButton);
        OtherRadioButton.setText("Other");
        OtherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRadioButtonActionPerformed(evt);
            }
        });

        patientTypeLabel.setText("Patient Type");

        patientCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal Patient", "Critical Patient", " " }));
        patientCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientComboboxActionPerformed(evt);
            }
        });

        ImageButton.setText("Upload Image");
        ImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(ImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(patientTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(patientCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addComponent(MaleRadioButon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OtherRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FnameTxtField)
                                    .addComponent(LnameTxtField)
                                    .addComponent(AgeTxtField)
                                    .addComponent(EmailTxtField)
                                    .addComponent(MessageTxtFIeld, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addComponent(Imagedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaleRadioButon)
                    .addComponent(FemaleRadioButton)
                    .addComponent(OtherRadioButton))
                .addGap(29, 29, 29)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MessageTxtFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Imagedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameTxtFieldFocusLost
        // TODO add your handling code here:
        String Fname = FnameTxtField.getText();
        if(!isValidName(Fname))
        {
            JOptionPane.showMessageDialog(this, "Invalid First Name", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            FnameTxtField.requestFocus();
        }
    }//GEN-LAST:event_FnameTxtFieldFocusLost

    private void LnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameTxtFieldFocusLost
        // TODO add your handling code here:
        String Lname = LnameTxtField.getText();
        if(!isValidName(Lname))
        {
            JOptionPane.showMessageDialog(this, "Invalid Last Name", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            LnameTxtField.requestFocus();
        }
    }//GEN-LAST:event_LnameTxtFieldFocusLost

    private void AgeTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeTxtFieldFocusLost
        // TODO add your handling code here:
        String age = AgeTxtField.getText().trim();
        if(!age.isEmpty() && !isValidInteger(age))
        {
            JOptionPane.showMessageDialog(this, "Invalid Age", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            AgeTxtField.requestFocus();
        }
    }//GEN-LAST:event_AgeTxtFieldFocusLost

    private void EmailTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailTxtFieldFocusLost
        // TODO add your handling code here:
        String email = EmailTxtField.getText();
        if(!isValidEmail(email))
        {
            JOptionPane.showMessageDialog(this, "Please provide proper Email Address", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            EmailTxtField.requestFocus();
        }
    }//GEN-LAST:event_EmailTxtFieldFocusLost

    private void SubmitbuttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SubmitbuttonFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitbuttonFocusLost

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed
        // TODO add your handling code here:
        Patient patient = new Patient();
        patient.setFirstName(FnameTxtField.getText());
        patient.setLastName(LnameTxtField.getText());
        patient.setAge(AgeTxtField.getText());
        patient.setEmail(EmailTxtField.getText());
        patient.setGender(GenderButtonGroup.getSelection().getActionCommand());
        patient.setMessage(MessageTxtFIeld.getText());
        patient.setFilePath(Filepath);
        String Fname = FnameTxtField.getText();
        String Lname = LnameTxtField.getText();
        String age   = AgeTxtField.getText();
        String email = EmailTxtField.getText();
        String gender = GenderButtonGroup.getSelection().getActionCommand();
        String patientType = patientCombobox.getSelectedItem().toString();
        String Message = MessageTxtFIeld.getText();
        
      
        if (Fname.trim().isEmpty()||Lname.trim().isEmpty()||age.trim().isEmpty()|| email.trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please fill in all the details", "Incomplete Form", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            System.out.println("First name: " + Fname);
            System.out.println("Last name: " + Lname);
            System.out.println("Age: " + age);
            System.out.println("Email: " + email);
            System.out.println("Gender: " + gender);
            System.out.println("Message" + Message);
            JOptionPane.showMessageDialog(null, "Registration successful!");
    }//GEN-LAST:event_SubmitbuttonActionPerformed
    ViewPanel newViewPanel = new ViewPanel(patient);
    bottomPanel.add(newViewPanel);
    CardLayout layout = (CardLayout) bottomPanel.getLayout();
    layout.next(bottomPanel);

    }

    private void MaleRadioButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioButonActionPerformed

    private void FemaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRadioButtonActionPerformed

    private void OtherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherRadioButtonActionPerformed

    private void patientComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientComboboxActionPerformed
    
    private String Filepath;
    private void ImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        ImageIcon icon = null ;
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                Filepath = file.getSelectedFile().getAbsolutePath();
                Image edited_image = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
                if (edited_image != null) {
                    icon = new ImageIcon(edited_image);
                } else {
                    throw new Exception();
                }
            } catch (Exception ex){}
        }

        Imagedisplay.setIcon(icon);
    }//GEN-LAST:event_ImageButtonActionPerformed

    private void MessageTxtFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageTxtFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessageTxtFIeldActionPerformed

    private void LnameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameTxtFieldActionPerformed
    private boolean isValidEmail(String email)
    {
        if (email.isEmpty() || email.trim().isEmpty()){
        return true; // Empty email is accepted
        }
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }
    
    private boolean isValidName(String name)
    {
        return name.matches("^$|^[A-Za-z\\s]+$");
    }
    
    private boolean isValidInteger(String age)
    {        
    {
       if (age.isEmpty() || age == null) {
            return true; // Empty string is accepted
        }

        try {
            int ageint = Integer.parseInt(age);

            // Check if the age is within a valid range
            if (ageint >= 0 && ageint <= 150) {
                return true; // Valid age
            } else {
                return false; // Age is out of range
            }
        } catch (NumberFormatException e) {
            return false; // Not a valid integer
        }
    } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTxtField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxtField;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JLabel FnameLabel;
    private javax.swing.JTextField FnameTxtField;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JButton ImageButton;
    private javax.swing.JLabel Imagedisplay;
    private javax.swing.JLabel LnameLabel;
    private javax.swing.JTextField LnameTxtField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MaleRadioButon;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField MessageTxtFIeld;
    private javax.swing.JRadioButton OtherRadioButton;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> patientCombobox;
    private javax.swing.JLabel patientTypeLabel;
    // End of variables declaration//GEN-END:variables
}