/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Patient;
import java.awt.Image;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    
    private Patient newPatient;
    public ViewPanel(Patient patient) {
        initComponents();
        this.newPatient = patient;
        getData();
    }
    
    private void getData() {
        FnameTxtField.setText(this.newPatient.getFirstName());
        LnameTxtField.setText(this.newPatient.getLastName());
        AgeTxtField.setText(this.newPatient.getAge());
        EmailTxtField.setText(this.newPatient.getEmail());
        patientCombobox.setActionCommand(this.newPatient.getPatientType());
        MessageTxtFIeld.setText(this.newPatient.getMessage());
        try {
                ImageIcon originalImageIcon = new ImageIcon(this.newPatient.getFilePath());
                Image originalImage = originalImageIcon.getImage();
//                Image resizedImage = originalImage.getScaledInstance(250, 250, Image.SCALE_IMAGE);
                Image resizedImage = originalImage.getScaledInstance(250, 250, Image.SCALE_SMOOTH);
                ImageIcon resizedImageIcon = new ImageIcon(resizedImage);
//                uploadedImageIcon = resizedImageIcon;
                Imagedisplay.setIcon(resizedImageIcon);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        ButtonModel selectedRadioButton = GenderButtonGroup.getSelection();
        //System.out.println("Action Command: " + selectedRadioButton.getActionCommand());
        if(selectedRadioButton != null){
            String selectedGender = selectedRadioButton.getActionCommand().toUpperCase();


            switch(selectedGender){
                case "MALE":
                    MaleRadioButon.setSelected(true);
                    break;
                case "FEMALE":
                    FemaleRadioButton.setSelected(true);
                    break;
                case "OTHER":
                    OtherRadioButton.setSelected(true);
                    break;

            }

        }
           else {
              System.err.println("please select gender");
         }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FnameLabel = new javax.swing.JLabel();
        LnameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        MessageLabel = new javax.swing.JLabel();
        FnameTxtField = new javax.swing.JTextField();
        LnameTxtField = new javax.swing.JTextField();
        AgeTxtField = new javax.swing.JTextField();
        EmailTxtField = new javax.swing.JTextField();
        MessageTxtFIeld = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        MaleRadioButon = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        OtherRadioButton = new javax.swing.JRadioButton();
        patientType = new javax.swing.JLabel();
        patientCombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Imagedisplay = new javax.swing.JLabel();

        MainPanel.setBackground(new java.awt.Color(255, 255, 204));
        MainPanel.setPreferredSize(new java.awt.Dimension(450, 500));

        Title.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Title.setText("View Form");

        FnameLabel.setText("First Name");

        LnameLabel.setText("Last Name");

        AgeLabel.setText("Age");

        EmailLabel.setText("Email");

        MessageLabel.setText("Message");

        FnameTxtField.setText(" ");
        FnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FnameTxtFieldFocusLost(evt);
            }
        });

        LnameTxtField.setText(" ");
        LnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameTxtFieldFocusLost(evt);
            }
        });

        AgeTxtField.setText(" ");
        AgeTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AgeTxtFieldFocusLost(evt);
            }
        });

        EmailTxtField.setText(" ");
        EmailTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailTxtFieldFocusLost(evt);
            }
        });

        MessageTxtFIeld.setText(" ");
        MessageTxtFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageTxtFIeldActionPerformed(evt);
            }
        });

        GenderLabel.setText("Gender");

        MaleRadioButon.setText("Male");
        MaleRadioButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButonActionPerformed(evt);
            }
        });

        FemaleRadioButton.setText("Female");
        FemaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioButtonActionPerformed(evt);
            }
        });

        OtherRadioButton.setText("Other");
        OtherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRadioButtonActionPerformed(evt);
            }
        });

        patientType.setText("Patient Type");

        patientCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal Patient", "Critical Patient", " " }));
        patientCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addComponent(MaleRadioButon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FemaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OtherRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(patientType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FnameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(LnameTxtField)
                                        .addComponent(AgeTxtField)
                                        .addComponent(EmailTxtField))
                                    .addComponent(MessageTxtFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Imagedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaleRadioButon)
                    .addComponent(FemaleRadioButton)
                    .addComponent(OtherRadioButton))
                .addGap(32, 32, 32)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MessageTxtFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Imagedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameTxtFieldFocusLost
        // TODO add your handling code here: 
        String Fname = FnameTxtField.getText();
        if(!isValidName(Fname))
        {
            JOptionPane.showMessageDialog(this, "Invalid First Name", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            FnameTxtField.requestFocus();
        }
    }//GEN-LAST:event_FnameTxtFieldFocusLost

    private void LnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameTxtFieldFocusLost
        // TODO add your handling code here:
        String Lname = LnameTxtField.getText();
        if(!isValidName(Lname))
        {
            JOptionPane.showMessageDialog(this, "Invalid Last Name", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            LnameTxtField.requestFocus();
        }
    }//GEN-LAST:event_LnameTxtFieldFocusLost

    private void AgeTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeTxtFieldFocusLost
        // TODO add your handling code here:
        String age = AgeTxtField.getText().trim();
        if(!age.isEmpty() && !isValidInteger(age))
        {
            JOptionPane.showMessageDialog(this, "Invalid Age", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            AgeTxtField.requestFocus();
        }
    }//GEN-LAST:event_AgeTxtFieldFocusLost

    private void EmailTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailTxtFieldFocusLost
        // TODO add your handling code here:
        String email = EmailTxtField.getText();
        if(!isValidEmail(email))
        {
            JOptionPane.showMessageDialog(this, "Please provide proper Email Address", "Wrong Input", JOptionPane.ERROR_MESSAGE);
            EmailTxtField.requestFocus();
        }
    }//GEN-LAST:event_EmailTxtFieldFocusLost
  
    private boolean isValidEmail(String email)
    {
        if (email.isEmpty() || email.trim().isEmpty()){
        return true; // Empty email is accepted
        }
        return email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }
    
    private boolean isValidName(String name)
    {
        return name.matches("^$|^[A-Za-z\\s]+$");
    }
    
    private boolean isValidInteger(String age)
    {        
    {
       if (age.isEmpty() || age == null) {
            return true; // Empty string is accepted
        }

        try {
            int ageint = Integer.parseInt(age);

            // Check if the age is within a valid range
            if (ageint >= 0 && ageint <= 150) {
                return true; // Valid age
            } else {
                return false; // Age is out of range
            }
        } catch (NumberFormatException e) {
            return false; // Not a valid integer
        }
    } 
    }
    
    
    private void MaleRadioButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioButonActionPerformed

    private void FemaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleRadioButtonActionPerformed

    private void OtherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherRadioButtonActionPerformed

    private void patientComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientComboboxActionPerformed

    private void MessageTxtFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageTxtFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessageTxtFIeldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTxtField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxtField;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JLabel FnameLabel;
    private javax.swing.JTextField FnameTxtField;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel Imagedisplay;
    private javax.swing.JLabel LnameLabel;
    private javax.swing.JTextField LnameTxtField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MaleRadioButon;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField MessageTxtFIeld;
    private javax.swing.JRadioButton OtherRadioButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> patientCombobox;
    private javax.swing.JLabel patientType;
    // End of variables declaration//GEN-END:variables

}
